### ISSUE TITLE
Demo crashes on mobile

### ISSUE THREAD

**Issue by mattiapontonio** [tofsjonas/sortable#11]
![Screenshot_20201011-150303.png](https://user-images.githubusercontent.com/44380480/95679420-fcf6c300-0bd2-11eb-95e7-b6fb9081985e.png)

🙂

**Comment by tofsjonas** [comment]
You are right. I guess it uses a bit too much ram or processing power. Fun times!

**Comment by mattiapontonio** [comment]
> You are right. I guess it uses a bit too much ram or processing power. Fun times!

Maybe it's out of scope but maybe:
- less data
- kind of pagination

**Comment by tofsjonas** [comment]
Yeah, it's a bit outside the scope of this. It was never meant to be a table handler, only to add sorting to an existing one. A table with that much data should probably be dealt with some other way...

**Comment by mattiapontonio** [comment]
> Yeah, it's a bit outside the scope of this. It was never meant to be a table handler, only to add sorting to an existing one. A table with that much data should probably be dealt with some other way...

Your repo but can You update the table with less data ...?

**Comment by tofsjonas** [comment]
I did. It still doesn't work? Damn, that's no good... 😒

**Comment by mattiapontonio** [comment]
Yes now It works 🤳🙋

**Comment by tofsjonas** [comment]
Whew. 😅 Thanks for the heads up! 😊
