### ISSUE TITLE
[Proposal] extend HTMLTableElement | HTMLTableSectionElement

### ISSUE THREAD

**Issue by mattiapontonio** [tofsjonas/sortable#12]
How about extend this DOM interface so no CSS classes are needed?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableElement

Something like
```javascript
HTMLTableElement.prototype.sort = function(){}
```

Or maybe better this interface that Is the body

https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableSectionElement

**Comment by shellisabatini** [comment]
I want to change the dark grey color on the header row but can't seem to make it work.  Can anyone help please?
