### ISSUE TITLE
Size sort

### ISSUE THREAD

**Issue by MichaelM00** [tofsjonas/sortable#15]
Thanks for this sort library @tofsjonas

I tried sortable.mega-advanced but it seems to fail at size sort for some formats such as 100.55 KiB. Is it possible to make sorting work for these kind of values as well?

**Comment by tofsjonas** [comment]
My first thought is to use the advanced solution instead, where sorting is done based on the data-sort attribute, and prepare the table before sorting. And by prepare I mean loop thru and convert textContent=100.55 KiB into a data-sort="123456"

(To be honest I don't really get what I was thinking when I built the mega-advanced version. 😬🤔)

**Comment by tofsjonas** [comment]
If you look at https://tofsjonas.github.io/sortable/ you will see what I mean. Check the source for the solution

Or you could alter the `getValue()` to do basically the same thing.
