### ISSUE TITLE
Header only clickable once

### ISSUE THREAD

**Issue by 0hwow** [tofsjonas/sortable#21]
Great code! I am testing the demo in WP and I can only click the headers once (ascending order). Thank you.

**Comment by tofsjonas** [comment]
Thank you :)

Does this happen in any wordpress install?

Do you have an example where I can see it in action? I haven't used wordpress in forever...

**Comment by 0hwow** [comment]
Hi, please check the table at [https://colaterall.com/inicio/](url)
Thanks :)

**Comment by tofsjonas** [comment]
Well, it seems this file : `https://colaterall.com/wp-content/uploads/siteground-optimizer-assets/siteground-optimizer-combined-js-c8aa9cf66e162ea71932f4e489d6c3ed.js` is included twice in the html, which means the event listener will be added twice and therefore triggered twice each time you click.

Pretty cool, it sorts the table twice and you can't even see it blink! 😉😉

**Comment by 0hwow** [comment]
Beautiful! Thank you 🙏

**Comment by 0hwow** [comment]
hi

hope all’s well

thank you for your contributions, your work is great

I’m having trouble with the following code

help please?

much appreciated :)

best

o.w.
