### ISSUE TITLE
Deploy latest version to GitHub Pages

### ISSUE THREAD

**Issue by marcphilipp** [tofsjonas/sortable#26]
Thanks for the neat little library! 👍 

It seems the deployed version at https://tofsjonas.github.io/sortable/sortable.js is outdated. Could you please deploy the latest there? I think the easiest would be to get rid of the `gh-pages` branch and change the repo config to deploy to GitHub Pages from `main` instead.

**Comment by tofsjonas** [comment]
I had no idea that that was even possible. Thanks! 😊
