### ISSUE TITLE
Sort on load

### ISSUE THREAD

**Issue by Issen007** [tofsjonas/sortable#27]
Hi,
Is it possible to get this sorting by a default column and on `load` instead of `click`?

**Comment by Issen007** [comment]
Found a work-around. 
By adding 

```
document.getElementById('finish-time').click();
```
In the end of the script it automatically sort my page during load. *LOL*

**Comment by abitsalihu** [comment]
Hey @Issen007 , you can also add an event listener to the page so that when the HTML file renders a function can fire off which can have that "sort" function. 

e.x
 window.addEventListener("load", function(){
       "add your logic here"
})

**Comment by tofsjonas** [comment]
Yup. @abitsalihu's way would be my way.

```javascript

window.addEventListener('load', function () {
  const el = document.getElementById('finish-time')
  if (el) {
    el.click()
  }
})
```

**Comment by abitsalihu** [comment]
@tofsjonas haha, glad to help. :)

**Comment by tofsjonas** [comment]
I will put it in the readme! Thanks guys! 😊

**Comment by Issen007** [comment]
Thanks
