### ISSUE TITLE
Enhancement request: positioning of sort indicator

### ISSUE THREAD

**Issue by axlekb** [tofsjonas/sortable#29]
The sort indicator is positioned using `::after`.  Any interest in adding a class to allow it to be optionally positioned `::before` as well?

The use case would be for right aligned columns.  Currently the `::after` adds extra space which results in the header column not lining up with the body columns.

#### Example: Right alignment issue
<img width="72" alt="image" src="https://user-images.githubusercontent.com/2972314/200185342-eb2f312b-1faa-438c-a05d-4e5508f7b259.png">

#### Example: positioning indicator using `::before`
<img width="78" alt="image" src="https://user-images.githubusercontent.com/2972314/200185293-30960bf6-5367-4175-878a-b2bece95044e.png">

**Comment by tofsjonas** [comment]
Er, I added the css more as an example. It was never meant to be used "for real".

I guess it would be the same as with **no-sort**, either add `class` + `css` or plain `css`

It looks like you've already done this; if you would like to share your code I can put it in the readme 😊
