### ISSUE TITLE
Sorting doesn't work in some cases

### ISSUE THREAD

**Issue by chatcoda** [tofsjonas/sortable#30]
Good and concise work !
I noticed what could be considered a bug.
Consider the following table:
<table class="sortable">
	<thead><tr><th class=" dir-d ">Field</th></tr></thead>
	<tbody><tr><td>0</td></tr><tr><td>&nbsp;</td></tr><tr><td>0</td></tr><tr><td>&nbsp;</td></tr></tbody>
	<tfoot></tfoot>
</table>
Sorting does not work because (at line 110 of sortable.js) isNaN(x - y) always returns false, since JavaScript interprets an empty string as zero.
It could be fixed in several ways (regex, parseInt, trim + test empty string, maybe typeof, ...)
This should do the trick: isNaN(parseInt(x) - parseInt(y))

**Comment by 0hwow** [comment]
I’ll give a try, bit busy :)

thanks
