### ISSUE TITLE
re-sort for changed data

### ISSUE THREAD

**Issue by markg85** [tofsjonas/sortable#32]
Hi,

I have a table where data flows in over time.
Clicking the header to sort is:
- A manual action
- And sorts in the reverse order that it was presented in (by design)

So i'm looking for a way to re-sort the data without clicking the header. Just resort with the current setting (asc or desc).

**Comment by tofsjonas** [comment]
Hey,

Some kind of click event _is_ required, so I guess something like this:

```javascript
function resortTable() {
  const element = document.querySelector('.sortable th[class*=dir-]')
  if (element) {
    element.click()
    element.click()
  }
}
```

**Comment by markg85** [comment]
Ha, smart! Just emulating a click twice ;)

Still, I very much prefer to not needlessly do sorting. Emulating a click twice is definitely wasting resources and might even be problematic in large tables.

**Comment by tofsjonas** [comment]
True.

And double click is what I recommend for sort on load, so there we have the same issue. I guess I could add a timeout, so it's only sorted once. 🤔

I'll give it a try...

**Comment by tofsjonas** [comment]
No. A timeout will pollute the global whatchamacallit. Curses.

This is not super pretty, but it _will_ sort the table only once:

```javascript
function resortTable() {
  const element = document.querySelector('.sortable th[class*=dir-]')
  if (element) {
    var reg = / dir-(u|d) /
    var class_name = element.className
    var before = reg.exec(class_name)[1]
    var after = before === 'u' ? 'd' : 'u'

    var new_class = class_name.replace(reg, ' ') + ' dir-' + after + ' '
    element.className = new_class
    element.click()
  }
}
```

**Comment by markg85** [comment]
Ha :)

I see what you're doing there. Smart!
And it works just fine too!

I take it that you want to keep all logic in the event handler. As if not then you could consider making a global function that just sorts the table given properties passed into the function. It would make it trivial to re-sort.

**Comment by tofsjonas** [comment]
Yeah, I like that it has a life completely on its own, not touching the global namespace(!) 🤷
