### ISSUE TITLE
Prefex support for Kilo, Mega, Giga, ...

### ISSUE THREAD

**Issue by dumtux** [tofsjonas/sortable#33]
When I have a table like this,

Name   | Value
-----------|-----------
Party A | 250
Party B | 1.2k
Party C | 16200
Party D | 2.8M

Is there a way to make sorting correct.y?

**Comment by tofsjonas** [comment]
That's what the data-sort attribute is for:

```html
...
<td>Party B</td>
<td data-sort="1228.8">1.2k</td>
...
<td>Party D</td>
<td data-sort="2936012.8">2.8M</td>
...
```

Are you the one generating the html table? Or do you need to solve this with javascript only?

**Comment by dumtux** [comment]
Thank you.
I generate the table from JSON data, thus, this can solve my problem quickly.
