### ISSUE TITLE
Sorted data

### ISSUE THREAD

**Issue by data-handler** [tofsjonas/sortable#39]
I have data that has been pre-sorted on the server before being displayed in the client.

How could I indicate which column the data is already sorted by.

I tried adding the 'dir-u' class to the th, but when the same column is sorted via a mouse click, it ends up with two classes: 'dir-u' and 'dir-d'

**Comment by tofsjonas** [comment]
Yeah, since **ie9** doesn't support `classlist`, I had to add ' dir-u ' and ' dir-d ' with spaces, so they wouldn't interfere with other classes.

If you add spaces 'dir-u' => ' dir-u ' it should work!

**Comment by data-handler** [comment]
I am generating the html client side. If i try to add ' dir- u ' to the elements classList, I get an error

**Comment by data-handler** [comment]
OKay. If I use className, it works. Thanks

**Comment by data-handler** [comment]
Sorry, but do we care about IE9 anymore?

**Comment by tofsjonas** [comment]
Haha, not really, it's mainly for sentimental reasons

**Comment by tofsjonas** [comment]
But you are right, it is time to let ie9 go. This horrible solution hurts more than saying goodbye.

Thanks for giving me the final push!

**Comment by data-handler** [comment]
👍
