### ISSUE TITLE
Secondary sort

### ISSUE THREAD

**Issue by GordanRatkovic** [tofsjonas/sortable#44]
To illustrate a practical example:

I have a table with many rows, each row has a year property.
If I sort by year all entries with the same year are grouped, but within that group, their order is random.

Is there a way to sort by a certain column/property, but also specify a secondary sort (applied when the primary sort values are the same)?

Right off the bat, I imagine I could do something like `data-sort="2022-projectname"` where I concatenate the year and desired property, but I was wondering if there's perhaps a different way...

Thanks for the help, love the library!

**Comment by tofsjonas** [comment]
Ooo, I like it, thanks for the suggestion. 🙏

The implementation wasn't horribly difficult, BUT it drove the package over 1k!!!! 😭

I'll have a PR any minute

**Comment by GordanRatkovic** [comment]
Ayyyy, bad news for the package size. But thanks for making this feature happen. Big props!
