### ISSUE TITLE
Performance improvement suggestions

### ISSUE THREAD

**Issue by baryluk** [tofsjonas/sortable#46]
Huge thanks for great library. So much packed in so few lines of code! :)

Some suggestions:

Final append is done not so efficiently:

```typescript
        while (rows.length) {
          clone_tbody.appendChild(rows.splice(0, 1)[0])
        }
```

=>

```typescript
        clone_tbody.append(...rows)
```

or

```typescript
        let l = rows.length;
        for (let j = 0; j < l; j++) {
          clone_tbody.appendChild(rows[j])
        }
```

Sorting also could be optimized, especially when more than one tbody is present, or no tie breaker specified, by doing specialization before the tBodies loop:

```typescript
      const tiebreaker = parseInt(element.dataset.sortTbr)

...
    for (let i = 0; i < table.tBodies.length; i++) {
...

        rows.sort(function (a: HTMLTableRowElement, b: HTMLTableRowElement) {
          const bool = compare(a, b, column_index)
          return bool === 0 && !isNaN(tiebreaker) ? compare(a, b, tiebreaker) : bool
        })
...
    }
```

=>

```typescript
      const tiebreaker = parseInt(element.dataset.sortTbr)

      let comparator = compare;
      if (!isNaN(tiebreaker)) {
        comparator = function (a: HTMLTableRowElement, b: HTMLTableRowElement) {
          const bool = compare(a, b, column_index)
          return bool === 0  ? compare(a, b, tiebreaker) : bool
        }
      }

    for (let i = 0; i < table.tBodies.length; i++) {

...
        rows.sort(comparator)
...
    }
```

Same technique can be used for reversing:

```typescript
      const compare = (a: HTMLTableRowElement, b: HTMLTableRowElement, index: number) => {
        const x = getValue((reverse ? a : b).cells[index])
        const y = getValue((reverse ? b : a).cells[index])
        const temp = parseFloat(x) - parseFloat(y)
        const bool = isNaN(temp) ? x.localeCompare(y) : temp
        return bool
      }
```

=>

use `if (reverse)` to create one of two functions before passing to `sort`, instead of doing same check inside the function. The last one probably is not super beneficial, as smart JIT might specialize it automatically speculatively. Benchmarks required.

**Comment by tofsjonas** [comment]
First off, thanks for your thoughts!

I don't remember why I used splice instead of just a normal for loop. The for loop makes a lot more sense, but I guess I had _some_ reason, good or bad 🤷 (I remember chasing single bytes back when it was still around 600B, but since the while loop is actually more characters than the for loop, who knows what I was thinking)

These days, spread makes even more sense. I think it's a tiny bit slower than a for loop, but not significantly so.

**Comment by tofsjonas** [comment]
About optimizing the sorting, it has always been a tradeoff between size and efficiency. Even though the 1000 byte barrier has been broken, I still like to keep it as small as possible.

(The spread-thingy brought it under 1k, thank you for that! 🙏) 

Your suggestion would be an improvement when it comes to speed, but it would add "many" lines of code. If someone experiences significant lag, I guess it would be worth investigating, but atm I am just too lazy 😬
