### ISSUE TITLE
no-sort too strict?

### ISSUE THREAD

**Issue by Daviid-P** [tofsjonas/sortable#47]
I tried to add filter inputs to the header to hide or show rows onKeyDown but the `no-sort` class won't let me click on the inputs to search.

What would be better, ignore the click if TH has the class in javascript or moving the filter inputs outside the table?

![chrome_SvkSXeRaQV](https://user-images.githubusercontent.com/7734808/228187192-a186c527-9302-4647-a1df-2542712d70fc.png)

**Comment by tofsjonas** [comment]
Could you put them in a separate row where the `th` doesn't have have `no-sort`?

**Comment by tofsjonas** [comment]
Wait! You can have `td` inside `thead`, then sortable wouldn't be triggered! 🥳

**Comment by tofsjonas** [comment]
Like so:

```html
<table class="sortable">
  <thead>
    <tr>
      <td>
        <input type="text" />
      </td>
      <td>
        <input type="text" />
      </td>
    </tr>
    <tr>
      <th>id</th>
      <th class="no-sort">Cuenta Contable</th>
    </tr>
  </thead>
  <tbody>
```

**Comment by Daviid-P** [comment]
Yes, that works.

I tried with `th` first and got the direction arrows and couldn't click the inputs without sorting.
