### ISSUE TITLE
Empty rows always last possible?

### ISSUE THREAD

**Issue by nepsilon** [tofsjonas/sortable#54]
Is it possible to make empty rows always last after sorting? Similar to what SQL does with `ORDER BY foo NULLS LAST`.

So that no matter ascending or descending sort is applied on a column, empty values will always be at the bottom.

**Comment by tofsjonas** [comment]
I don't see why not. Thanks for your suggestion! 😊️

**Comment by tofsjonas** [comment]
Looks like you discovered a much older bug. Cool. Thanks again! 🙏️
