### ISSUE TITLE
A11y Aria not updating when toggled.

### ISSUE THREAD

**Issue by swirtSJW** [tofsjonas/sortable#66]
In using both
https://cdn.jsdelivr.net/gh/tofsjonas/sortable@latest/sortable.min.js
https://cdn.jsdelivr.net/gh/tofsjonas/sortable@latest/sortable.a11y.min.js

When a heading is clicked on and the sort changes, the aria does not change

![image](https://github.com/tofsjonas/sortable/assets/5752113/9c2ded68-b7b4-4c64-a670-2ea900199a39)

Notice the dir-* changes but the aria does not
![image](https://github.com/tofsjonas/sortable/assets/5752113/70922ac7-523f-4989-acc5-f8d0b878e1c4)

This also seems to prevent the aria based css from engaging.

**Comment by tofsjonas** [comment]
I _think_ this could be a caching issue, dir-d and dir-u aren't used anymore.. 🤔🤞

**Comment by swirtSJW** [comment]
I cleared my browser cache.  I still get the same results.  Unless perhaps https://cdn.jsdelivr.net/gh/tofsjonas/sortable@latest/sortable.min.js is cached at the CDN and is outdated?  I'm not really sure.

**Comment by swirtSJW** [comment]
This cleared itself up without intervention.  I am guessing this was a cdn issue  :man_shrugging:   Thanks for looking into it.  I am closing this issue.  Sorry for the confusion.
