### ISSUE TITLE
Not found on jsdelivr.net

### ISSUE THREAD

**Issue by ThomasLandauer** [tofsjonas/sortable#68]
When trying to install this using [Symfony's CLI command](https://symfony.com/doc/current/frontend/asset_mapper.html#importing-3rd-party-javascript-packages):
```bash
php bin/console importmap:require sortable-tablesort
```
... I'm getting:
> Error 404 requiring packages from jsDelivr for "sortable-tablesort". Check your package names. Response: Couldn't find the requested file.
> HTTP/2 404  returned for "https://cdn.jsdelivr.net/npm/sortable-tablesort@3.1.0/+esm".

Is this an issue of this project? Or Symfony? Or jsDelivr?

**Comment by tofsjonas** [comment]
I had no idea that was possible. I'll have a look!

**Comment by tofsjonas** [comment]
Ok,

It's probably because I don't build the project "properly", with `esm` and `cjs` builds. 🤦

Some day I will fix that, but for now, maybe something like this will work?

```
import sortable from 'https://cdn.jsdelivr.net/npm/sortable-tablesort@3.1.0/sortable.js';
```

**Comment by ThomasLandauer** [comment]
The point of this `require` command is that it gives you the option to check for updates (later on). This is of course lost when importing a fixed version.
But thanks anyway, for now I just wanted to find out whose responsibility it is to make the magic work ;-)

**Comment by tofsjonas** [comment]
Ok, I added

```json
  "main": "sortable.min.js",
  "module": "sortable.min.js",
```

to package.json and now this url exists: <https://cdn.jsdelivr.net/npm/sortable-tablesort@3.2.0/+esm>

I don't know if `php bin/console importmap:require sortable-tablesort` will work, but the url looks kind of the same, so hopefully! 🤞

**Comment by ThomasLandauer** [comment]
Yeah, thanks, the main part works now! :-)

But the CSS part doesn't. I had to manually add it by doing `php bin/console importmap:require sortable-tablesort/sortable.min.css`, but it should be detected somehow automatically.

https://symfony.com/doc/current/frontend/asset_mapper.html#importing-3rd-party-javascript-packages just says:
> If a package includes a main CSS file, that will also be added

Do you have any idea how this could work? How could you declare a CSS file as being "the one"?

**Comment by tofsjonas** [comment]
Hm. I can try:

```json
  "style": "sortable.min.css",
  "sass": "src/sortable.css",
```

That's what they are doing in bootstrap..

**Comment by tofsjonas** [comment]
Ok, `3.2.1` ftw!

**Comment by tofsjonas** [comment]
...aaaand correct path in `3.2.2` 🥳

**Comment by ThomasLandauer** [comment]
Cool - that works! :-) The CSS entry is added automatically:
```bash
$ php bin/console importmap:require sortable-tablesort

[OK] 2 new items (sortable-tablesort, sortable-tablesort/sortable.min.css) added to the importmap.php!
```
So I'm closing here - thanks!
