### ISSUE TITLE
Numeric Sort Option

### ISSUE THREAD

**Issue by BFranklinAmsive** [tofsjonas/sortable#72]
Hey there. Me, again. Have you considered adding a numeric sort option? I know we can currently implement a custom value using the data-sort attribute, however, a native option to sort a column numerically would be awesome. 

Current use case, a client has weights entered into a comparison table and they want to sort those values numerically. Currently, without any customization, there is no differentiation between alphanumeric and numeric sorting in the script (that I am aware of, anyway).

I was going to see about adding a numeric sort option using a classname, similar to "no-sort", and wanted to check with you to see if that is already a thing or if it's something you're considering for a future release.

**Comment by tofsjonas** [comment]
Unless I broke something numeric sorting should be supported 🤔

In the `compare` function on lines 109-110:

```ts
  ...
   const temp = Number(x) - Number(y)
   const bool = isNaN(temp) ? x.localeCompare(y) : temp
  ...
```
