### ISSUE TITLE
Feature request: Add a mechanism for excluding columns from sorting

### ISSUE THREAD

**Issue by AdamDawes** [tofsjonas/sortable#77]
I would very much like to number each rows in my sortable table. The important thing is that the row numbers should not change when the table is re-sorted. So for example, if my original table is as follows:

| Row Number | Name | Release Year |
|-|-|-|
| 1 | Half-Life | 1998 |
| 2 | Counter-Strike | 2004 |
| 3 | Portal | 2007 |
| 4 | Left 4 Dead | 2008 |

...when I click (e.g.) `Name`, I would like the table to re-sort as normal, except that the values in the `Row Number` column would not be included in the sort operation and would retain their original order, resulting in the following table:

| Row Number | Name ▲ | Release Year |
|-|-|-|
| 1 | Counter-Strike | 2004 |
| 2 | Half-Life | 1998 |
| 3 | Left 4 Dead | 2008 |
| 4 | Portal | 2007 |

The most flexible approach would perhaps be to support a new class such as `ignore-sort`. This would have the same effects as `no-sort` (the column itself would not be sortable) but would additionally prevent changes to the column data order when *other* columns are sorted.

Alternatively some mechanism of explicitly marking a column as a "row-number column" and allowing sortable to generate the row numbers automatically would be sufficient for my purposes, though is not as flexible.

**Comment by tofsjonas** [comment]
Interesting idea.

I guess the main problem is that we aren't sorting columns, we are sorting rows. So for this to work with JavaScript we would have to pass data from one row to another and alter the content of the table cells, which is asking for trouble.

Fortunately, _this_ specific issue can be solved with CSS!

```html
<style>
  .row-number-column tbody {
    counter-reset: rowNumber; /* Initialize the counter */
  }

  .row-number-column tbody tr {
    counter-increment: rowNumber; /* Increment the counter for each row */
  }

  .row-number-column tbody tr td:first-child::before {
    content: counter(rowNumber); /* Display the counter value */
  }
</style>
<table class="sortable row-number-column">
  <thead>
    <tr>
      <th class="no-sort">Row-Number</th>
      <th>Name</th>
      <th>Release Year</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td></td>
      <td>Counter-Strike</td>
      <td>2004</td>
    </tr>
    <tr>
      <td></td>
      <td>Half-Life</td>
      <td>1998</td>
    </tr>
    <tr>
      <td></td>
      <td>Left 4 Dead</td>
      <td>2008</td>
    </tr>
    <tr>
      <td></td>
      <td>Portal</td>
      <td>2007</td>
    </tr>
  </tbody>
</table>
```
🥳

**Comment by AdamDawes** [comment]
Now that is an excellent idea, which I hadn't thought of at all. I'll give this a try tomorrow and see how it works, thanks very much for that suggestion!

**Comment by AdamDawes** [comment]
Works a treat, thank you. The only minor side-effect of this approach is that the text within the row-number column is not selectable (due to not really being present within the table) and so can't be copied to the clipboard, but that's not of significance in my use case so I'll ignore that. 👍
